### ISSUE TITLE
windows 10 64bit tools menu

### ISSUE THREAD

**Issue by daelv** [216k155/lux#102]
open wallet configuration file default app requested.
open masternode config also?
![image](https://user-images.githubusercontent.com/24859041/37072108-cb8aaa48-218d-11e8-88d1-fb8fc480c7dc.png)

**Comment by daelv** [comment]
from a fellow user I think win 7:
"I had to close an reopen last night to do the send because it wasn't showing my mined  LUX in my balance, they have a bug in their wallet not updating most recent balance to send feature.
Closing and reopening, client update turned on.
OK, it should send now, it got stuck in some send cache because the balance doesn't update with client open."

**Comment by 216k155** [comment]
Please check it out: https://github.com/216k155/lux/releases
Close !!!
