### ISSUE TITLE
Wallet needs reindex on every startup.

### ISSUE THREAD

**Issue by poolhyper** [216k155/lux#107]
Using Ubuntu 16.04 daemon. If i build the daemon and allow to sync fully it runs fine. If i then stop the daemon and then restart, I get the following...

Error loading block database.
Do you want to rebuild the block database now?

I can only get the wallet to start again if i use the -reindex option but it will do the same on EVERY restart.

Any thoughts?

Cheers

**Comment by goodthebest** [comment]
Yes, same  behavior at my end too.

**Comment by rej156** [comment]
Fixed reassuringly in the upcoming release!

**Comment by rej156** [comment]
https://github.com/216k155/lux/issues/109 related @nguyenhoangtran11
