### ISSUE TITLE
Issue after make

### ISSUE THREAD

**Issue by leaenbinario** [216k155/lux#108]
-- Installing: /home/lea/wallets/lux/src/cpp-ethereum/deps/bin/wasm-reduce
make[4]: Leaving directory '/home/lea/wallets/lux/src/cpp-ethereum/deps/src/binaryen-build'
[ 18%] Completed 'binaryen'
make[3]: Leaving directory '/home/lea/wallets/lux/src/cpp-ethereum'
[ 18%] Built target binaryen
make[2]: Leaving directory '/home/lea/wallets/lux/src/cpp-ethereum'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lea/wallets/lux/src/cpp-ethereum'
Makefile:601: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

I can resolve it, any suggestion please?

**Comment by nguyenhoangtran11** [comment]
What OS are you using? What target OS (eg: Win 64 bits, Macs or Linux) do you intend to build?

**Comment by leaenbinario** [comment]
Ubuntu 16.04.
Finally I resolved the issue, 
I changed to another directory and started again. I`m mining now, 
thx!

**Comment by nguyenhoangtran11** [comment]
There is no issue with the build. I will close the issue now
