### ISSUE TITLE
LuxCore Wallet crashes on Win 10 

### ISSUE THREAD

**Issue by KyferEz** [216k155/lux#109]
Luxcore Win x64 wallet constantly crashes. This prevents staking from ever activating and makes it difficult to download blockchain. This started happening as of the update to 4.0 and got MUCH worse on the update to 4.2.

**Comment by nguyenhoangtran11** [comment]
Hi,

I'm sorry to hear that. Could you please follow this link and send me the crash logs?
https://helpx.adobe.com/photoshop-elements-editor/using/find-crashlogs.html

Thank for your report. Again, I'm sorry for this convenience

**Comment by KyferEz** [comment]
Emailed to your yahoo email account.

**Comment by daelv** [comment]
getting this on win x64 at close. 
![image](https://user-images.githubusercontent.com/24859041/37552099-98339002-2984-11e8-90cb-1b1600e88702.png)

**Comment by KyferEz** [comment]
For me it's not just at closure; it also during running that it crashes.

**Comment by nguyenhoangtran11** [comment]
Hi,

I'm sorry for making you waiting. Could you please use this workaround: "use the private key import/export procedure to create a new wallet.dat (or find a backup that does not crash)"?

**Comment by 216k155** [comment]
Please check it out : https://github.com/216k155/lux/releases
Close !!!
