### ISSUE TITLE
LUX Wallet 4.2.0.0 no sync 

### ISSUE THREAD

**Issue by cmlpc** [216k155/lux#118]
LUX Core version v4.2.0.0-160ec8d (32-bit)
Hi. My LUX wallet basically doesn't sync. It stays at "21 weeks behind" and no further movement.
Please help.
Thank you.
cmlpc

**Comment by nguyenhoangtran11** [comment]
Please send me debug.log at C:\Users\<account name>\AppData\Roaming\LUX for further investigation

**Comment by cmlpc** [comment]
[debug.log](https://github.com/216k155/lux/files/1840724/debug.log)
Hi. Here is the debug.log. After some time it crashes with a fatal error.
Can't put this wallet to work.
Appreciate your support.
Thanks.

**Comment by cmlpc** [comment]
Any news???

**Comment by nguyenhoangtran11** [comment]
Hi,

Could you please use the private key import/export procedure to create a new wallet.dat (or find a backup that does not crash)?

**Comment by cmlpc** [comment]
It is not that wallet.dat in particular. I've tried in different computers, different wallets, the same result....
Using Win10 64. Everything is normal. I use a lot of wallets. This one is the only one with issues....

**Comment by cmlpc** [comment]
Like described before, and on the logs, the issue is "Synchronizing from the network" very slowly, almost stopped. It stucks at around 21 / 20 weeks behind and crashes. I've tried in 2 different computers with new wallets. The same result: not working. And finnaly, it crashes.

**Comment by cmlpc** [comment]
I've tried what you recomend, but exactly the same result: nothing new...

**Comment by cmlpc** [comment]
I made it!! It is working, but seems very unstabble - shows an error any time we close the wallet.

**Comment by cmlpc** [comment]
It is working after opening wallet again. But you guys should look at these unstability.

**Comment by nguyenhoangtran11** [comment]
Hi,
This issue should be fixed in the commit https://github.com/216k155/lux/commit/ee8f9a4db800f905f904998e1b3bbe79f1c620f5 now. 

Therefore, I'd like to close this issue

**Comment by cmlpc** [comment]
Now I lost my wallet:
![image](https://user-images.githubusercontent.com/37640865/37876461-90252274-3044-11e8-80ad-6a17307c738c.png)
Cannot open backups....
