### ISSUE TITLE
Rejected blocks

### ISSUE THREAD

**Issue by goodthebest** [216k155/lux#120]
@216k155 
I setup LUX into a yiimp pool, however sadly end up getting blocks rejected and I'm wondering what made them rejected for **phi POW**

**here is log**
![image](https://user-images.githubusercontent.com/1715740/37815313-c8d9595a-2e87-11e8-8302-c341326e4f39.png)

**output cli that shows wallet version**
![image](https://user-images.githubusercontent.com/1715740/37815923-67a7d0aa-2e8a-11e8-9d72-2e29d4fba1eb.png)

**yiimp setting, we do not have any masternode, these are our pool admin setting**

![image](https://user-images.githubusercontent.com/1715740/37815720-6b92c644-2e89-11e8-8be5-e442d84ab0cd.png)

**here is lux.conf file**
![image](https://user-images.githubusercontent.com/1715740/37815788-bc1ab464-2e89-11e8-8f2b-3212d64519a2.png)

Any advice on how to fix blocks reject issue?

**Comment by rej156** [comment]
Closing as this was resolved via Discord, cheers!

**Comment by ETS5** [comment]
What was the solution as i got this error
