### ISSUE TITLE
4.3 crash at start

### ISSUE THREAD

**Issue by 008** [216k155/lux#122]
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: QObject::connect: Cannot connect (null)::triggered() to BitcoinGUI::showNormalIfMinimized()
GUI: QObject::connect: Cannot connect (null)::triggered() to BitcoinGUI::gotoSmartTokenPage()
GUI: QWidget::insertAction: Attempt to insert null action
GUI: setGeometry: Unable to set geometry 5x13+640+260 on QWidgetWindow/'QLabelClassWindow'. Resulting geometry:  120x13+640+260 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 0x0, maximum size: 16777215x16777215).

Win10 x64 lux-qt-wins.zip

**Comment by 216k155** [comment]
Please join our https://discord.gg/WUx5CT for support. Your log didn't show any crash issue. Close !!!

**Comment by fdoving** [comment]
I have this issue too. Directly crash at startup.

**Comment by fdoving** [comment]
Workaround:

Regedit
Go to:
HKEY_CURRENT_USER\Software\LUX\LUX-Qt

Delete all keys except strDataDir.

Worked for me anyway.
Need to set the your custom options again.

**Comment by nguyenhoangtran11** [comment]
Another thing, please use version 4.3.1. The issue should be fixed now

**Comment by fdoving** [comment]
Ok. Then the download link on luxcore.io is wrong, It links to 4.3.0.
