### ISSUE TITLE
Build fails on zmq compile

### ISSUE THREAD

**Issue by cpass78** [216k155/lux#134]
Running in order:

./install-dependencies.sh
./autogen.sh
./configure --disable-tests
make -j$(nproc)

on ubuntu 16.04 will eventually output the following and fail.

CXX      libbitcoin_wallet_a-instantx.o
zmq/zmqpublishnotifier.cpp: In function ‘int zmq_send_multipart(void*, const void*, size_t, ...)’:
zmq/zmqpublishnotifier.cpp:28:9: error: ‘zmq_msg_t’ was not declared in this scope
         zmq_msg_t msg;
         ^
zmq/zmqpublishnotifier.cpp:30:37: error: ‘msg’ was not declared in this scope
         int rc = zmq_msg_init_size(&msg, size);
                                     ^
zmq/zmqpublishnotifier.cpp:30:46: error: ‘zmq_msg_init_size’ was not declared in this scope
         int rc = zmq_msg_init_size(&msg, size);
                                              ^
zmq/zmqpublishnotifier.cpp:37:38: error: ‘zmq_msg_data’ was not declared in this scope
         void *buf = zmq_msg_data(&msg);
                                      ^
zmq/zmqpublishnotifier.cpp:42:46: error: ‘ZMQ_SNDMORE’ was not declared in this scope
         rc = zmq_msg_send(&msg, sock, data ? ZMQ_SNDMORE : 0);
                                              ^
zmq/zmqpublishnotifier.cpp:42:61: error: ‘zmq_msg_send’ was not declared in this scope
         rc = zmq_msg_send(&msg, sock, data ? ZMQ_SNDMORE : 0);
                                                             ^
zmq/zmqpublishnotifier.cpp:46:31: error: ‘zmq_msg_close’ was not declared in this scope
             zmq_msg_close(&msg);
                               ^
zmq/zmqpublishnotifier.cpp:50:27: error: ‘zmq_msg_close’ was not declared in this scope
         zmq_msg_close(&msg);
                           ^
zmq/zmqpublishnotifier.cpp: In member function ‘virtual bool CZMQAbstractPublishNotifier::Initialize(void*)’:
zmq/zmqpublishnotifier.cpp:69:40: error: ‘ZMQ_PUB’ was not declared in this scope
         psocket = zmq_socket(pcontext, ZMQ_PUB);
                                        ^
zmq/zmqpublishnotifier.cpp:69:47: error: ‘zmq_socket’ was not declared in this scope
         psocket = zmq_socket(pcontext, ZMQ_PUB);
                                               ^
zmq/zmqpublishnotifier.cpp:76:51: error: ‘zmq_bind’ was not declared in this scope
         int rc = zmq_bind(psocket, address.c_str());
                                                   ^
zmq/zmqpublishnotifier.cpp:80:30: error: ‘zmq_close’ was not declared in this scope
             zmq_close(psocket);
                              ^
zmq/zmqnotificationinterface.cpp: In function ‘void zmqError(const char*)’:
zmq/zmqnotificationinterface.cpp:15:74: error: ‘zmq_strerror’ was not declared in this scope
     LogPrint("zmq", "zmq: Error: %s, errno=%s\n", str, zmq_strerror(errno));
                                                                          ^
zmq/zmqpublishnotifier.cpp: In member function ‘virtual void CZMQAbstractPublishNotifier::Shutdown()’:
zmq/zmqpublishnotifier.cpp:122:33: error: ‘ZMQ_LINGER’ was not declared in this scope
         zmq_setsockopt(psocket, ZMQ_LINGER, &linger, sizeof(linger));
                                 ^
zmq/zmqpublishnotifier.cpp:122:68: error: ‘zmq_setsockopt’ was not declared in this scope
         zmq_setsockopt(psocket, ZMQ_LINGER, &linger, sizeof(linger));
                                                                    ^
zmq/zmqpublishnotifier.cpp:123:26: error: ‘zmq_close’ was not declared in this scope
         zmq_close(psocket);
                          ^
zmq/zmqnotificationinterface.cpp: In member function ‘bool CZMQNotificationInterface::Initialize()’:
zmq/zmqnotificationinterface.cpp:80:26: error: ‘zmq_init’ was not declared in this scope
     pcontext = zmq_init(1);
                          ^
zmq/zmqnotificationinterface.cpp: In member function ‘void CZMQNotificationInterface::Shutdown()’:
zmq/zmqnotificationinterface.cpp:123:33: error: ‘zmq_ctx_destroy’ was not declared in this scope
         zmq_ctx_destroy(pcontext);
                                 ^
Makefile:4714: recipe for target 'zmq/libbitcoin_zmq_a-zmqpublishnotifier.o' failed
make[2]: *** [zmq/libbitcoin_zmq_a-zmqpublishnotifier.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:4700: recipe for target 'zmq/libbitcoin_zmq_a-zmqnotificationinterface.o' failed
make[2]: *** [zmq/libbitcoin_zmq_a-zmqnotificationinterface.o] Error 1
CXX      libbitcoin_wallet_a-instantx.o
zmq/zmqpublishnotifier.cpp: In function ‘int zmq_send_multipart(void*, const void*, size_t, ...)’:
zmq/zmqpublishnotifier.cpp:28:9: error: ‘zmq_msg_t’ was not declared in this scope
         zmq_msg_t msg;
         ^
zmq/zmqpublishnotifier.cpp:30:37: error: ‘msg’ was not declared in this scope
         int rc = zmq_msg_init_size(&msg, size);
                                     ^
zmq/zmqpublishnotifier.cpp:30:46: error: ‘zmq_msg_init_size’ was not declared in this scope
         int rc = zmq_msg_init_size(&msg, size);
                                              ^
zmq/zmqpublishnotifier.cpp:37:38: error: ‘zmq_msg_data’ was not declared in this scope
         void *buf = zmq_msg_data(&msg);
                                      ^
zmq/zmqpublishnotifier.cpp:42:46: error: ‘ZMQ_SNDMORE’ was not declared in this scope
         rc = zmq_msg_send(&msg, sock, data ? ZMQ_SNDMORE : 0);
                                              ^
zmq/zmqpublishnotifier.cpp:42:61: error: ‘zmq_msg_send’ was not declared in this scope
         rc = zmq_msg_send(&msg, sock, data ? ZMQ_SNDMORE : 0);
                                                             ^
zmq/zmqpublishnotifier.cpp:46:31: error: ‘zmq_msg_close’ was not declared in this scope
             zmq_msg_close(&msg);
                               ^
zmq/zmqpublishnotifier.cpp:50:27: error: ‘zmq_msg_close’ was not declared in this scope
         zmq_msg_close(&msg);
                           ^
zmq/zmqpublishnotifier.cpp: In member function ‘virtual bool CZMQAbstractPublishNotifier::Initialize(void*)’:
zmq/zmqpublishnotifier.cpp:69:40: error: ‘ZMQ_PUB’ was not declared in this scope
         psocket = zmq_socket(pcontext, ZMQ_PUB);
                                        ^
zmq/zmqpublishnotifier.cpp:69:47: error: ‘zmq_socket’ was not declared in this scope
         psocket = zmq_socket(pcontext, ZMQ_PUB);
                                               ^
zmq/zmqpublishnotifier.cpp:76:51: error: ‘zmq_bind’ was not declared in this scope
         int rc = zmq_bind(psocket, address.c_str());
                                                   ^
zmq/zmqpublishnotifier.cpp:80:30: error: ‘zmq_close’ was not declared in this scope
             zmq_close(psocket);
                              ^
zmq/zmqnotificationinterface.cpp: In function ‘void zmqError(const char*)’:
zmq/zmqnotificationinterface.cpp:15:74: error: ‘zmq_strerror’ was not declared in this scope
     LogPrint("zmq", "zmq: Error: %s, errno=%s\n", str, zmq_strerror(errno));
                                                                          ^
zmq/zmqpublishnotifier.cpp: In member function ‘virtual void CZMQAbstractPublishNotifier::Shutdown()’:
zmq/zmqpublishnotifier.cpp:122:33: error: ‘ZMQ_LINGER’ was not declared in this scope
         zmq_setsockopt(psocket, ZMQ_LINGER, &linger, sizeof(linger));
                                 ^
zmq/zmqpublishnotifier.cpp:122:68: error: ‘zmq_setsockopt’ was not declared in this scope
         zmq_setsockopt(psocket, ZMQ_LINGER, &linger, sizeof(linger));
                                                                    ^
zmq/zmqpublishnotifier.cpp:123:26: error: ‘zmq_close’ was not declared in this scope
         zmq_close(psocket);
                          ^
zmq/zmqnotificationinterface.cpp: In member function ‘bool CZMQNotificationInterface::Initialize()’:
zmq/zmqnotificationinterface.cpp:80:26: error: ‘zmq_init’ was not declared in this scope
     pcontext = zmq_init(1);
                          ^
zmq/zmqnotificationinterface.cpp: In member function ‘void CZMQNotificationInterface::Shutdown()’:
zmq/zmqnotificationinterface.cpp:123:33: error: ‘zmq_ctx_destroy’ was not declared in this scope
         zmq_ctx_destroy(pcontext);
                                 ^
Makefile:4714: recipe for target 'zmq/libbitcoin_zmq_a-zmqpublishnotifier.o' failed
make[2]: *** [zmq/libbitcoin_zmq_a-zmqpublishnotifier.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:4700: recipe for target 'zmq/libbitcoin_zmq_a-zmqnotificationinterface.o' failed
make[2]: *** [zmq/libbitcoin_zmq_a-zmqnotificationinterface.o] Error 1

**Comment by cpass78** [comment]
Did the above and same result

**Comment by nguyenhoangtran11** [comment]
If possible, please contact me on discord for further assistant
