### ISSUE TITLE
Lux Wallet v4.3.0 - Windows - Will not open

### ISSUE THREAD

**Issue by mwodzynski** [216k155/lux#138]
The wallet opened first time, synced fine. I was able to send some coin to the wallet. 

Now when trying to open, I get white window for a about 1 sec then it turns off and nothing happens. 

Running Windows 10 Pro ver. 1709

Let me know if you need more info...

**Comment by nguyenhoangtran11** [comment]
Please send me the debug.log at C:\Users\<Username>\AppData\Roaming\LUX

**Comment by mwodzynski** [comment]
[debug.log](https://github.com/216k155/lux/files/1997294/debug.log)

**Comment by nguyenhoangtran11** [comment]
1) Backup your wallet.dat to a safe place
2) Remove all files in C:\Users<Username>\AppData\Roaming\LUX, except wallet.dat
3) Run the wallet again and waiting for it to sync completely

Please let me know if it is working

**Comment by nguyenhoangtran11** [comment]
Another thing, please make sure that there is no wallet instance running before you start the wallet

**Comment by Inception69** [comment]
Wallet was running fine then decided to crash for no reason. Now it will not start or install.
Looking at the log posted by mwodzynski, I have the same issue logged as him.

There is obviously an issue with the way that QT is handling png versions and needs to be fixed asap.
I cannot even install this on a brand new Win 10 PC that I have just finished building tonight. 

I created a backup of my old log as it was huge and let a new one be created. See the attached log.  This is after attempting to start the wallet 3 times.

Doing as you,  nguyenhoangtran11  have suggested does not work as now, once you try to install the wallet, it asks you for the location to install but when you try, it fails on install and not all of the files get extracted.

[debug.log](https://github.com/216k155/lux/files/1997520/debug.log)

**Comment by nguyenhoangtran11** [comment]
Does the issue still  happen with our latest version (4.3.1)?

**Comment by nguyenhoangtran11** [comment]
This issue is fixed at version 4.3.1. Please use our latest binary version or compile the code from master branch. Hence, I will close this ticket

**Comment by Inception69** [comment]
Download the binary from where? Only source is listed.

**Comment by mwodzynski** [comment]
4.3.1 compiled version is not available. Only source code is listed. 

Removing files and rerunning 4.3.0 did not help.
