### ISSUE TITLE
LUX qt crashes on Linux (core dump)

### ISSUE THREAD

**Issue by hbentel** [216k155/lux#146]
On Ubuntu 16.04.3 LTS (Xenial Xerus)
Running LUX QT: Luxcore version v4.3.0.0-6914294-Luxcore (64-bit)
Error from console:

*** Error in `./lux-qt': malloc(): smallbin double linked list corrupted: 0x0000000002d68ae0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f6c60f807e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x82651)[0x7f6c60f8b651]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f6c60f8d184]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x18)[0x7f6c6187fe78]
./lux-qt[0x8a719a]
./lux-qt[0x8aa5f7]
./lux-qt[0x8a9ae4]
./lux-qt[0x8aa369]
./lux-qt[0x6dcd2a]
./lux-qt[0x7fdd04]
./lux-qt[0x805358]
./lux-qt[0x505415]
./lux-qt[0x59eee5]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x7ea)[0x7f6c633d1d2a]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN6QTimer10timerEventEP11QTimerEvent+0x28)[0x7f6c633de5c8]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0xa3)[0x7f6c633d2bb3]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c)[0x7f6c63d1405c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x256)[0x7f6c63d19516]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0xdb)[0x7f6c633a338b]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN14QTimerInfoList14activateTimersEv+0x52d)[0x7f6c633f85ed]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2dbb29)[0x7f6c633f8b29]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7f6c6014e197]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4a3f0)[0x7f6c6014e3f0]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7f6c6014e49c]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7f6c633f97cf]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x10a)[0x7f6c633a0b4a]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x9c)[0x7f6c633a8bec]
./lux-qt[0x454956]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f6c60f29830]
./lux-qt[0x461fd9]
======= Memory map: ========
00400000-00c93000 r-xp 00000000 fd:01 1035177                            /home/henrik/lux/lux-qt
00e92000-00ead000 r--p 00892000 fd:01 1035177                            /home/henrik/lux/lux-qt
00ead000-00eae000 rw-p 008ad000 fd:01 1035177                            /home/henrik/lux/lux-qt
00eae000-00eaf000 rw-p 00000000 00:00 0 
00eaf000-00f05000 rw-p 00000000 00:00 0 
017a7000-036f4000 rw-p 00000000 00:00 0                                  [heap]
036f4000-036f5000 rw-p 00000000 00:00 0                                  [heap]
036f5000-05ccf000 rw-p 00000000 00:00 0                                  [heap]
7f6be0000000-7f6be3fce000 rw-p 00000000 00:00 0 
7f6be3fce000-7f6be4000000 ---p 00000000 00:00 0 
7f6be8000000-7f6bf0000000 rw-p 00000000 00:00 0 
7f6bf0000000-7f6bf4000000 rw-p 00000000 00:00 0 
7f6bf6530000-7f6bf6743000 r--s 00000000 fd:01 2068947                    /home/henrik/.lux/blocks/index/001449.ldb
7f6bf6d87000-7f6bf6f91000 r--s 00000000 fd:01 2068321                    /home/henrik/.lux/chainstate/012484.ldb
7f6bf6f91000-7f6bf71a4000 r--s 00000000 fd:01 2068942                    /home/henrik/.lux/blocks/index/001448.ldb
7f6bf71a4000-7f6bf73b7000 r--s 00000000 fd:01 2068941                    /home/henrik/.lux/blocks/index/001447.ldb
7f6bf73b7000-7f6bf75ca000 r--s 00000000 fd:01 2068326                    /home/henrik/.lux/blocks/index/001446.ldb
7f6bf79db000-7f6bf7be4000 r--s 00000000 fd:01 2066686                    /home/henrik/.lux/blocks/index/001418.ldb
7f6bf7ded000-7f6bf8000000 r--s 00000000 fd:01 2068135                    /home/henrik/.lux/blocks/index/001445.ldb
7f6bf8000000-7f6bf8083000 rw-p 00000000 00:00 0 
7f6bf8083000-7f6bfc000000 ---p 00000000 00:00 0 
7f6bfc000000-7f6bfc050000 rw-p 00000000 00:00 0 
7f6bfc050000-7f6c00000000 ---p 00000000 00:00 0 
7f6c00000000-7f6c000bf000 rw-p 00000000 00:00 0 
7f6c000bf000-7f6c04000000 ---p 00000000 00:00 0 
7f6c04000000-7f6c04050000 rw-p 00000000 00:00 0 
7f6c04050000-7f6c08000000 ---p 00000000 00:00 0 
7f6c08000000-7f6c087c3000 rw-p 00000000 00:00 0 
7f6c087c3000-7f6c0c000000 ---p 00000000 00:00 0 
7f6c0c000000-7f6c0c04c000 rw-p 00000000 00:00 0 
7f6c0c04c000-7f6c10000000 ---p 00000000 00:00 0 
7f6c10000000-7f6c13fff000 rw-p 00000000 00:00 0 
7f6c13fff000-7f6c14000000 ---p 00000000 00:00 0 
7f6c141d4000-7f6c143e7000 r--s 00000000 fd:01 2068131                    /home/henrik/.lux/blocks/index/001444.ldb
7f6c143e7000-7f6c145f0000 r--s 00000000 fd:01 2066346                    /home/henrik/.lux/blocks/index/001436.ldb
7f6c145f1000-7f6c147f9000 r--s 00000000 fd:01 2068112                    /home/henrik/.lux/chainstate/012482.ldb
7f6c147f9000-7f6c147fa000 ---p 00000000 00:00 0 
7f6c147fa000-7f6c14ffa000 rw-p 00000000 00:00 0 
7f6c14ffa000-7f6c14ffb000 ---p 00000000 00:00 0 
7f6c14ffb000-7f6c157fb000 rw-p 00000000 00:00 0 
7f6c157fb000-7f6c157fc000 ---p 00000000 00:00 0 
7f6c157fc000-7f6c15ffc000 rw-p 00000000 00:00 0 
7f6c15ffc000-7f6c15ffd000 ---p 00000000 00:00 0 
7f6c15ffd000-7f6c167fd000 rw-p 00000000 00:00 0 
7f6c167fd000-7f6c167fe000 ---p 00000000 00:00 0 
7f6c167fe000-7f6c16ffe000 rw-p 00000000 00:00 0 
7f6c16ffe000-7f6c16fff000 ---p 00000000 00:00 0 
7f6c16fff000-7f6c177ff000 rw-p 00000000 00:00 0 
7f6c177ff000-7f6c17800000 ---p 00000000 00:00 0 
7f6c17800000-7f6c18000000 rw-p 00000000 00:00 0 
7f6c18000000-7f6c18e17000 rw-p 00000000 00:00 0 
7f6c18e17000-7f6c1c000000 ---p 00000000 00:00 0 
7f6c1c000000-7f6c1c055000 rw-p 00000000 00:00 0 
7f6c1c055000-7f6c20000000 ---p 00000000 00:00 0 
7f6c20000000-7f6c2004b000 rw-p 00000000 00:00 0 
7f6c2004b000-7f6c24000000 ---p 00000000 00:00 0 
7f6c241df000-7f6c243e7000 r--s 00000000 fd:01 2066682                    /home/henrik/.lux/blocks/index/001415.ldb
7f6c247f9000-7f6c247fa000 ---p 00000000 00:00 0 
7f6c247fa000-7f6c24ffa000 rw-p 00000000 00:00 0 
7f6c24ffa000-7f6c24ffb000 ---p 00000000 00:00 0 
7f6c24ffb000-7f6c257fb000 rw-p 00000000 00:00 0 
7f6c257fb000-7f6c257fc000 ---p 00000000 00:00 0 
7f6c257fc000-7f6c25ffc000 rw-p 00000000 00:00 0 
7f6c25ffc000-7f6c25ffd000 ---p 00000000 00:00 0 
7f6c25ffd000-7f6c267fd000 rw-p 00000000 00:00 0 
7f6c267fd000-7f6c267fe000 ---p 00000000 00:00 0 
7f6c267fe000-7f6c26ffe000 rw-p 00000000 00:00 0 
7f6c26ffe000-7f6c26fff000 ---p 00000000 00:00 0 
7f6c26fff000-7f6c277ff000 rw-p 00000000 00:00 0 
7f6c277ff000-7f6c27800000 ---p 00000000 00:00 0 
7f6c27800000-7f6c28000000 rw-p 00000000 00:00 0 
7f6c28000000-7f6c2a5a7000 rw-p 00000000 00:00 0 
7f6c2a5a7000-7f6c2c000000 ---p 00000000 00:00 0 
7f6c2c000000-7f6c30000000 rw-p 00000000 00:00 0 
7f6c301a4000-7f6c303b7000 r--s 00000000 fd:01 2068292                    /home/henrik/.lux/blocks/index/001457.ldb
7f6c303b7000-7f6c305c0000 r--s 00000000 fd:01 2066318                    /home/henrik/.lux/blocks/index/001435.ldb
7f6c307c8000-7f6c307c9000 ---p 00000000 00:00 0 
7f6c307c9000-7f6c30fc9000 rw-p 00000000 00:00 0 
7f6c311c1000-7f6c313cf000 r--s 00000000 fd:01 2068134                    /home/henrik/.lux/blocks/index/001456.ldb
7f6c313cf000-7f6c315d8000 r--s 00000000 fd:01 2068132                    /home/henrik/.lux/blocks/index/001455.ldb
7f6c318ce000-7f6c31ad8000 r--s 00000000 fd:01 2066324                    /home/henrik/.lux/chainstate/012530.ldb
7f6c31ad8000-7f6c31ce1000 r--s 00000000 fd:01 2066559                    /home/henrik/.lux/blocks/index/001454.ldb
7f6c31ce1000-7f6c31ee9000 r--s 00000000 fd:01 2066385                    /home/henrik/.lux/blocks/index/001453.ldb
7f6c31ee9000-7f6c320f2000 r--s 00000000 fd:01 2066366                    /home/henrik/.lux/blocks/index/001452.ldb
7f6c322f9000-7f6c3250c000 r--s 00000000 fd:01 2066352                    /home/henrik/.lux/blocks/index/001441.ldb
7f6c32710000-7f6c3291b000 r--s 00000000 fd:01 2066380                    /home/henrik/.lux/chainstate/012506.ldb
7f6c3291b000-7f6c32c38000 rw-s 00000000 00:05 1765212172                 /SYSV00000000 (deleted)
7f6c32db7000-7f6c32fc0000 r--s 00000000 fd:01 2066330                    /home/henrik/.lux/blocks/index/001451.ldb
7f6c32fc5000-7f6c331ce000 r--s 00000000 fd:01 2066679                    /home/henrik/.lux/chainstate/012498.ldb
7f6c335da000-7f6c337e2000 r--s 00000000 fd:01 2066348                    /home/henrik/.lux/chainstate/012502.ldb
7f6c337e2000-7f6c339ec000 r--s 00000000 fd:01 2066618                    /home/henrik/.lux/chainstate/012524.ldb
7f6c339ec000-7f6c339f1000 r-xp 00000000 fd:01 58194                      /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f6c339f1000-7f6c33bf1000 ---p 00005000 fd:01 58194                      /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f6c33bf1000-7f6c33bf2000 r--p 00005000 fd:01 58194                      /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f6c33bf2000-7f6c33bf3000 rw-p 00006000 fd:01 58194                      /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7f6c33df7000-7f6c34000000 r--s 00000000 fd:01 2066362                    /home/henrik/.lux/chainstate/012505.ldb
7f6c34000000-7f6c34105000 rw-p 00000000 00:00 0 
7f6c34105000-7f6c38000000 ---p 00000000 00:00 0 
7f6c38000000-7f6c3c000000 rw-p 00000000 00:00 0 
7f6c3c1a3000-7f6c3c3ab000 r--s 00000000 fd:01 2066354                    /home/henrik/.lux/chainstate/012496.ldb
7f6c3c3ab000-7f6c3c5b3000 r--s 00000000 fd:01 2066361                    /home/henrik/.lux/chainstate/012504.ldb
7f6c3c5b3000-7f6c3c5ca000 r-xp 00000000 fd:01 58188                      /lib/x86_64-linux-gnu/libresolv-2.23.so
7f6c3c5ca000-7f6c3c7ca000 ---p 00017000 fd:01 58188                      /lib/x86_64-linux-gnu/libresolv-2.23.so
7f6c3c7ca000-7f6c3c7cb000 r--p 00017000 fd:01 58188                      /lib/x86_64-linux-gnu/libresolv-2.23.so
7f6c3c7cb000-7f6c3c7cc000 rw-p 00018000 fd:01 58188                      /lib/x86_64-linux-gnu/libresolv-2.23.so
7f6c3c7cc000-7f6c3c7ce000 rw-p 00000000 00:00 0 
7f6c3c7d5000-7f6c3c9dd000 r--s 00000000 fd:01 2066358                    /home/henrik/.lux/chainstate/012533.ldb
7f6c3c9dd000-7f6c3c9df000 r-xp 00000000 fd:01 75936                      /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f6c3c9df000-7f6c3cbde000 ---p 00002000 fd:01 75936                      /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f6c3cbde000-7f6c3cbdf000 r--p 00001000 fd:01 75936                      /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f6c3cbdf000-7f6c3cbe0000 rw-p 00002000 fd:01 75936                      /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f6c3cddf000-7f6c3cfe7000 r--s 00000000 fd:01 2066625                    /home/henrik/.lux/blocks/index/001404.ldb
7f6c3cfe7000-7f6c3d1f0000 r--s 00000000 fd:01 2066342                    /home/henrik/.lux/chainstate/012532.ldb
7f6c3d1f0000-7f6c3d3f8000 r--s 00000000 fd:01 2066388                    /home/henrik/.lux/blocks/index/001403.ldb
7f6c3d402000-7f6c3d60c000 r--s 00000000 fd:01 2066334                    /home/henrik/.lux/chainstate/012500.ldb
7f6c3d60c000-7f6c3d815000 r--s 00000000 fd:01 2066665                    /home/henrik/.lux/blocks/index/001412.ldb
7f6c3d815000-7f6c3da1c000 r--s 00000000 fd:01 2066677                    /home/henrik/.lux/chainstate/012525.ldb
7f6c3da1c000-7f6c3da1d000 ---p 00000000 00:00 0 
7f6c3da1d000-7f6c3e21d000 rw-p 00000000 00:00 0 
7f6c3e36e000-7f6c3e577000 r--s 00000000 fd:01 2066332                    /home/henrik/.lux/chainstate/012531.ldb
7f6c3e77e000-7f6c3e983000 r--s 00000000 fd:01 2068293                    /home/henrik/.lux/chainstate/012517.ldb
7f6c3e983000-7f6c3eb96000 r--s 00000000 fd:01 2068117                    /home/henrik/.lux/blocks/index/001443.ldb
7f6c3eb96000-7f6c3eda9000 r--s 00000000 fd:01 2066319                    /home/henrik/.lux/blocks/index/001440.ldb
7f6c3edb5000-7f6c3efba000 r--s 00000000 fd:01 2066927                    /home/henrik/.lux/chainstate/012515.ldb
7f6c3f1c3000-7f6c3f3cc000 r--s 00000000 fd:01 2066601                    /home/henrik/.lux/blocks/index/001410.ldb
7f6c3f3cc000-7f6c3f5d5000 r--s 00000000 fd:01 2066344                    /home/henrik/.lux/blocks/index/001400.ldb
7f6c3f5d8000-7f6c3f7e0000 r--s 00000000 fd:01 2066363                    /home/henrik/.lux/chainstate/012497.ldb
7f6c3f7e0000-7f6c3f9e7000 r--s 00000000 fd:01 2066925                    /home/henrik/.lux/chainstate/012526.ldb
7f6c3f9e7000-7f6c3fbf0000 r--s 00000000 fd:01 2066338                    /home/henrik/.lux/blocks/index/001399.ldb
7f6c3fbf1000-7f6c3fdf9000 r--s 00000000 fd:01 2066296                    /home/henrik/.lux/chainstate/012494.ldb
7f6c3fdf9000-7f6c40000000 r--s 00000000 fd:01 2066560                    /home/henrik/.lux/chainstate/012507.ldb
7f6c40000000-7f6c4004f000 rw-p 00000000 00:00 0 
7f6c4004f000-7f6c44000000 ---p 00000000 00:00 0 
7f6c44065000-7f6c4426c000 r--s 00000000 fd:01 2066378                    /home/henrik/.lux/chainstate/012478.ldb
7f6c4426c000-7f6c44473000 r--s 00000000 fd:01 2066411                    /home/henrik/.lux/chainstate/012534.ldb
7f6c44473000-7f6c44686000 r--s 00000000 fd:01 2066407                    /home/henrik/.lux/blocks/index/001442.ldb
7f6c44689000-7f6c4488e000 r--s 00000000 fd:01 2068305                    /home/henrik/.lux/chainstate/012518.ldb
7f6c4488e000-7f6c44a97000 r--s 00000000 fd:01 2066236                    /home/henrik/.lux/blocks/index/001408.ldb
7f6c44c35000-7f6c44e3c000 r--s 00000000 fd:01 2066336                    /home/henrik/.lux/chainstate/012501.ldb
7f6c44e3c000-7f6c44f85000 r--s 00000000 fd:01 2066599                    /home/henrik/.lux/blocks/index/001459.ldb
7f6c44f8b000-7f6c4507d000 r--s 00000000 fd:01 2068136                    /home/henrik/.lux/chainstate/012516.ldb
7f6c4507d000-7f6c45284000 r--s 00000000 fd:01 2066237                    /home/henrik/.lux/chainstate/012493.ldb
7f6c4528b000-7f6c45347000 r--s 00000000 fd:01 2068306                    /home/henrik/.lux/chainstate/012519.ldb
7f6c45347000-7f6c4554e000 r--s 00000000 fd:01 2066924                    /home/henrik/.lux/chainstate/012514.ldb
7f6c4565a000-7f6c45861000 r--s 00000000 fd:01 2067526                    /home/henrik/.lux/chainstate/012480.ldb
7f6c45861000-7f6c458de000 r--s 00000000 fd:01 2068309                    /home/henrik/.lux/chainstate/012522.ldb
7f6c458de000-7f6c45ae6000 r--s 00000000 fd:01 2066408                    /home/henrik/.lux/chainstate/012523.ldb
7f6c45ae9000-7f6c45cf2000 r--s 00000000 fd:01 2067525                    /home/henrik/.lux/chainstate/012479.ldb
7f6c45cf2000-7f6c45ef9000 r--s 00000000 fd:01 2066323                    /home/henrik/.lux/chainstate/012529.ldb
7f6c45ef9000-7f6c45faf000 r--s 00000000 fd:01 2066291                    /home/henrik/.lux/blocks/index/001434.ldb
7f6c45faf000-7f6c46061000 r--s 00000000 fd:01 2066157                    /home/henrik/.lux/blocks/index/001433.ldb
7f6c46061000-7f6c460b5000 r--p 00000000 fd:01 258148                     /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
7f6c460b5000-7f6c460f3000 r-xp 00000000 fd:01 1036661                    /usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqnmbearer.so
7f6c460f3000-7f6c460f5000 r--p 0003d000 fd:01 1036661                    /usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqnmbearer.so
7f6c460f5000-7f6c460f6000 rw-p 0003f000 fd:01 1036661                    /usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqnmbearer.so
7f6c460f6000-7f6c4612a000 r-xp 00000000 fd:01 1036660                    /usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqconnmanbearer.so
7f6c4612a000-7f6c4612b000 ---p 00034000 fd:01 1036660                    /usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqconnmanbearer.so
7f6c4612b000-7f6c4612c000 r--p 00034000 fd:01 1036660                    /usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqconnmanbearer.so
7f6c4612c000-7f6c4612d000 rw-p 00035000 fd:01 1036660                    /usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqconnmanbearer.so
7f6c461a5000-7f6c463ae000 r--s 00000000 fd:01 2066321                    /home/henrik/.lux/blocks/index/001397.ldb
7f6c464ba000-7f6c466c2000 r--s 00000000 fd:01 2066364                    /home/henrik/.lux/blocks/index/001401.ldb
7f6c466c2000-7f6c46822000 rw-s 00000000 00:05 1765146631                 /SYSV00000000 (deleted)
7f6c46822000-7f6c4682d000 r-xp 00000000 fd:01 58197                      /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f6c4682d000-7f6c46a2c000 ---p 0000b000 fd:01 58197                      /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f6c46a2c000-7f6c46a2d000 r--p 0000a000 fd:01 58197                      /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f6c46a2d000-7f6c46a2e000 rw-p 0000b000 fd:01 58197                      /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f6c46a2e000-7f6c46fb3000 rw-p 00000000 00:00 0 
7f6c46fcb000-7f6c46fd8000 r-xp 00000000 fd:01 1036659                    /usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqgenericbearer.so
7f6c46fd8000-7f6c46fd9000 ---p 0000d000 fd:01 1036659                    /usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqgenericbearer.so
7f6c46fd9000-7f6c46fda000 r--p 0000d000 fd:01 1036659                    /usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqgenericbearer.so
7f6c46fda000-7f6c46fdb000 rw-p 0000e000 fd:01 1036659                    /usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqgenericbearer.so
7f6c46fe2000-7f6c4701a000 r--s 00000000 fd:01 2068300                    /home/henrik/.lux/blocks/index/001458.ldb
7f6c4701a000-7f6c4710d000 r--s 00000000 fd:01 2069086                    /home/henrik/.lux/blocks/index/001450.ldb
7f6c4710d000-7f6c47118000 r-xp 00000000 fd:01 58201                      /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7f6c47118000-7f6c47317000 ---p 0000b000 fd:01 58201                      /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7f6c47317000-7f6c47318000 r--p 0000a000 fd:01 58201                      /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7f6c47318000-7f6c47319000 rw-p 0000b000 fd:01 58201                      /lib/x86_64-linux-gnu/libnss_nis-2.23.so
7f6c47319000-7f6c4732f000 r-xp 00000000 fd:01 58181                      /lib/x86_64-linux-gnu/libnsl-2.23.so
7f6c4732f000-7f6c4752e000 ---p 00016000 fd:01 58181                      /lib/x86_64-linux-gnu/libnsl-2.23.so
7f6c4752e000-7f6c4752f000 r--p 00015000 fd:01 58181                      /lib/x86_64-linux-gnu/libnsl-2.23.so
7f6c4752f000-7f6c47530000 rw-p 00016000 fd:01 58181                      /lib/x86_64-linux-gnu/libnsl-2.23.so
7f6c47530000-7f6c48000000 rw-p 00000000 00:00 0 
7f6c48000000-7f6c4804f000 rw-p 00000000 00:00 0 
7f6c4804f000-7f6c4c000000 ---p 00000000 00:00 0 
7f6c4c000000-7f6c4ffe0000 rw-p 00000000 00:00 0 
7f6c4ffe0000-7f6c50000000 ---p 00000000 00:00 0 
7f6c50000000-7f6c5004f000 rw-p 00000000 00:00 0 
7f6c5004f000-7f6c54000000 ---p 00000000 00:00 0 
7f6c54030000-7f6c54038000 r-xp 00000000 fd:01 58192                      /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7f6c54038000-7f6c54237000 ---p 00008000 fd:01 58192                      /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7f6c54237000-7f6c54238000 r--p 00007000 fd:01 58192                      /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7f6c54238000-7f6c54239000 rw-p 00008000 fd:01 58192                      /lib/x86_64-linux-gnu/libnss_compat-2.23.so
7f6c54259000-7f6c54298000 r--s 00000000 fd:01 2068303                    /home/henrik/.lux/blocks/index/001420.ldb
7f6c542dc000-7f6c542ee000 r--p 00000000 fd:01 1811124                    /usr/share/fonts/type1/gsfonts/n019004l.pfb
7f6c542ee000-7f6c5430f000 rw-s 00000000 00:05 1846870030                 /SYSV00000000 (deleted)
7f6c5430f000-7f6c54410000 rw-p 00000000 00:00 0 
7f6c54410000-7f6c54411000 ---p 00000000 00:00 0 
7f6c54411000-7f6c54c11000 rw-p 00000000 00:00 0 
7f6c54c11000-7f6c54c12000 ---p 00000000 00:00 0 
7f6c54c12000-7f6c55412000 rw-p 00000000 00:00 0 
7f6c55412000-7f6c55413000 ---p 00000000 00:00 0 
7f6c55413000-7f6c55c13000 rw-p 00000000 00:00 0 
7f6c55c13000-7f6c55cbf000 r--p 00000000 fd:01 258145                     /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
7f6c55cbf000-7f6c55d78000 r--p 00000000 fd:01 258146                     /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
7f6c55d78000-7f6c56079000 rw-p 00000000 00:00 0 
7f6c5607b000-7f6c5608c000 rw-s 00000000 00:05 1765638153                 /SYSV00000000 (deleted)
7f6c560b1000-7f6c560ba000 rw-s 00000000 00:05 1846804495                 /SYSV00000000 (deleted)
7f6c560ba000-7f6c5610d000 r-xp 00000000 fd:01 73173                      /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.5.1
7f6c5610d000-7f6c5610f000 r--p 00052000 fd:01 73173                      /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.5.1
7f6c5610f000-7f6c56111000 rw-p 00054000 fd:01 73173                      /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.5.1
7f6c56126000-7f6c56128000 r--s 00000000 fd:01 2066360                    /home/henrik/.lux/chainstate/012503.ldb
7f6c56128000-7f6c5617f000 r-xp 00000000 fd:01 58510                      /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f6c5617f000-7f6c5637f000 ---p 00057000 fd:01 58510                      /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f6c5637f000-7f6c56380000 r--p 00057000 fd:01 58510                      /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f6c56380000-7f6c56381000 rw-p 00058000 fd:01 58510                      /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f6c56382000-7f6c5638d000 r--s 00000000 fd:01 541283                     /var/cache/fontconfig/945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-6
7f6c5638d000-7f6c56391000 r--s 00000000 fd:01 537324                     /var/cache/fontconfig/d589a48862398ed80a3d6066f4f56f4c-le64.cache-6
7f6c56391000-7f6c56396000 r-xp 00000000 fd:01 1036725                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqsvg.so
7f6c56396000-7f6c56397000 r--p 00004000 fd:01 1036725                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqsvg.so
7f6c56397000-7f6c56398000 rw-p 00005000 fd:01 1036725                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqsvg.so
7f6c56398000-7f6c563a2000 r-xp 00000000 fd:01 1036713                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqjpeg.so
7f6c563a2000-7f6c563a3000 r--p 00009000 fd:01 1036713                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqjpeg.soAborted (core dumped)

**Comment by hbentel** [comment]
forgot, wallet was unlocked for staking at the time.

**Comment by nguyenhoangtran11** [comment]
This issue should be fixed in the version 4.3.2 now. Please contact our member in discord channel to get that version
