### ISSUE TITLE
Mac wallet 3.0.4 DMG installer is corrupted

### ISSUE THREAD

**Issue by daemonp** [216k155/lux#25]
Mac wallet downloaded from the release page DMG verifies ok but fails to mount

`no mountable file systems` 

![image](https://user-images.githubusercontent.com/5415/34916905-035b04c4-f937-11e7-8ba3-a22f226e3bc3.png)

**Comment by daemonp** [comment]
Works with High Sierra

**Comment by janantala** [comment]
Doesn't work with Sierra...

**Comment by rej156** [comment]
High sierra only atm till next wallet release end of the month
All recent mac osx versions from 10.10+ will be compatible post-release
