### ISSUE TITLE
luxsend.h:11:33: fatal error: masternode-payments.h

### ISSUE THREAD

**Issue by reloopbenny** [216k155/lux#27]
## **error code on Ubuntu 16.04 after make -j4 command!**

luxsend.h:11:33: fatal error: masternode-payments.h: Nincs ilyen fájl vagy könyvtár
compilation terminated.
Makefile:3818: recipe for target 'libbitcoin_server_a-init.o' failed
make[2]: *** [libbitcoin_server_a-init.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/pool/lux/src'
Makefile:7027: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pool/lux/src'
Makefile:593: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Pls help!

**Comment by rej156** [comment]
Hi,
Master is currently unstable until the upcoming next wallet 4.0 release
Please download the Linux wallet on the releases page here, until further notice 3.0.4 is the latest stable release.

**Comment by reloopbenny** [comment]
how can I run linux 3.0.4 release in command propt? I get libminiupnpc.so.8 error when I try to run it in commandline?!
