### ISSUE TITLE
doc/README.md has embarrassing wrong links

### ISSUE THREAD

**Issue by hbentel** [216k155/lux#29]
3 links are very wrong in the main README.md

1. "See the documentation at the LUX Wiki TODO for help and more information."
The LUX Wiki link points to "https://en.bitcoin.it/wiki/Main_Page"

2. "Ask for help on BitcoinTalk or on the LUX Forum."
The "BitcoinTalk" link points to the PIVX announcement page on bitcointalk 
https://bitcointalk.org/index.php?topic=1262920.0

3. "or on the LUX Forum" url points to http://forum.lux.org/ which doesn't exist.

**Comment by rej156** [comment]
Thanks for the shout out!
Welcome to the world of Bitcoin forks haha
Duely noted, git commit amendments incoming!
