### ISSUE TITLE
Issues solo mining

### ISSUE THREAD

**Issue by jadazul** [216k155/lux#30]
Hi! 

After some time trying to solo mine using the wallet (without any success, I should have discovered 2 blocks at least and still nothing), I discovered that at least something is wrong, comparing information coming from the Blockexplorer in the wallet and the information from any web blockexplorer (like https://chainz.cryptoid.info/lux/), the difficulty for the block is different most of the times. That same difference can bee seen when comparing the difficulty mining to the wallet (which sometimes is also lagging) and the one mining to a pool (Altminer.net, this one looks the same as the web blockhain explorer, so I'm guessing the issue is in the wallet itself).

Could you please check this and solve the issue? Maybe it's just visualization, or maybe it's really making my miner work on something that will never validate in the network... 

Thanks in advance! 

Btw, I'm using the version 3.0.4 for Windows, in Windows 10 Pro.

![lux-qt-issue](https://user-images.githubusercontent.com/26871891/35184565-5ccaea32-fdc5-11e7-9c3d-11019e8592fd.png)

**Comment by rej156** [comment]
New wallet release end of the month should fix these concerns, we are aware of them!

If it's still broke by then, holla on Discord or reopen another issue, serious stuff!
