### ISSUE TITLE
libdb_cxx-4.8.so error when running Linux wallet

### ISSUE THREAD

**Issue by namelike** [216k155/lux#31]
Hi, I get the following error message when trying to run the Linux wallet:

```
./lux-qt: error while loading shared libraries: libdb_cxx-4.8.so: cannot open shared object file: No such file or directory
```

I have searched for how to fix this, and all the results suggest to install the latest version of libdb++, but even after that the error still occurs.

**Comment by namelike** [comment]
Trying to build from source instead and I get the following error:

```
~/lux$ make -j4
Making all in src
make[1]: Entering directory '/home/namelike/lux/src'
make[2]: Entering directory '/home/namelike/lux/src'
  CXXLD    libbitcoinconsensus.la
  AR       univalue/libbitcoin_univalue.a
make[2]: *** No rule to make target 'masternode-budget.cpp', needed by 'libbitcoin_wallet_a-masternode-budget.o'.  Stop.
...
[Skipping a lot of boilerplate output here]
...
Makefile:593: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by rej156** [comment]
Please use the 3.0.4 download on the release page rather than compiling from source on the master branch until the next wallet release announcement, branch code is unstable ATM.

For future notice, feel free to use the one click builder scripts at the root of the repo dir

**Comment by rej156** [comment]
Work is being done on the staking branch if you're curious for tracking btw

**Comment by namelike** [comment]
To clarify, the 3.0.4 Linux download is what gave me the first error. I've tried multiple methods (including the Windows wallet) and have been unable to get a wallet up and running.
