### ISSUE TITLE
Lux Wallet Lag

### ISSUE THREAD

**Issue by blurb2m** [216k155/lux#32]
Running wallet 3.0.4 from 25NOV and it completely hangs my win 10 64-bit machine.
I can only click buttons inside the wallet 2 seconds out of every 30 seconds.
Closing the wallet usually makes me have to force close it.
Could we get another release build? lux-qt-wins.zip

**Comment by rej156** [comment]
Release builds coming before the end of the month!
Should fix a lot of things including this for sure!
