### ISSUE TITLE
Building in a FreeBSD jail

### ISSUE THREAD

**Issue by rtwair** [216k155/lux#34]
Hi,

Im trying to build this in a freebsd jail.
`FreeBSD wallet 11.0-STABLE FreeBSD 11.0-STABLE #0 r308738: Thu Nov 17 01:09:22 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64`

c++ headers are located bdb are located in:.
`/usr/local/include/db48`

However when I do a ./configure (after autogen.sh) I get the following error:.
`checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing`

I've tried to specify header while running ./configure:.
`BDB_CFLAGS="-I/usr/local/include/db48" BDB_LIBS="-L/usr/local/lib -ldb_cxx-4"`
also with libdb5
`BDB_CFLAGS="-I/usr/local/include/db5" BDB_LIBS="-L/usr/local/lib -ldb_cxx-5"`
_both are installed_

contents of header and library directories for bdb:.
`[wallet ~/lux]$ ls /usr/local/include/db48
db.h		db_185.h	db_cxx.h
[wallet ~/lux]$ ls /usr/local/include/db5/
db.h				dbstl_base_iterator.h		dbstl_dbc.h			dbstl_exception.h		dbstl_resource_manager.h	dbstl_vector.h
db_185.h			dbstl_common.h			dbstl_dbt.h			dbstl_inner_utility.h		dbstl_set.h
db_cxx.h			dbstl_container.h		dbstl_element_ref.h		dbstl_map.h			dbstl_utility.h
[wallet ~/lux]$ ls /usr/local/lib/*cxx*
/usr/local/lib/libdb_cxx-4.8.so		/usr/local/lib/libdb_cxx-5.3.so		/usr/local/lib/libdb_cxx-5.so		/usr/local/lib/libdb_cxx-6.2.so
/usr/local/lib/libdb_cxx-4.8.so.0	/usr/local/lib/libdb_cxx-5.3.so.0	/usr/local/lib/libdb_cxx-5.so.0`

Can you please help me? I'm eagerly awaiting to participate in your project.

Thank you

**Comment by oliveskin** [comment]
Can you check the readme : https://github.com/216k155/lux/blob/master/README.md
FreeBSD instructions have been updated.

Will leave this open until confirmed.

**Comment by rtwair** [comment]
Thanks for the quick response @oliveskin .

BTW the install_db.sh file is in the root of the git repo (not in contrib):.
`./contrib/install_db4.sh $(pwd) `

actually 
`./install_db4.sh $(pwd)`

The DB4 build completes successfully:.
`Installing DB include files: /usr/home/rtwair/lux/db4/include ...
Installing DB library: /usr/home/rtwair/lux/db4/lib ...
libtool: install: cp -p libdb-4.8.a /usr/home/rtwair/lux/db4/lib/libdb-4.8.a
libtool: install: chmod 644 /usr/home/rtwair/lux/db4/lib/libdb-4.8.a
libtool: install: ranlib /usr/home/rtwair/lux/db4/lib/libdb-4.8.a
libtool: install: cp -p libdb.a /usr/home/rtwair/lux/db4/lib/libdb.a
libtool: install: chmod 644 /usr/home/rtwair/lux/db4/lib/libdb.a
libtool: install: ranlib /usr/home/rtwair/lux/db4/lib/libdb.a
libtool: install: cp -p libdb_cxx-4.8.a /usr/home/rtwair/lux/db4/lib/libdb_cxx-4.8.a
libtool: install: chmod 644 /usr/home/rtwair/lux/db4/lib/libdb_cxx-4.8.a
libtool: install: ranlib /usr/home/rtwair/lux/db4/lib/libdb_cxx-4.8.a
libtool: install: cp -p libdb_cxx.a /usr/home/rtwair/lux/db4/lib/libdb_cxx.a
libtool: install: chmod 644 /usr/home/rtwair/lux/db4/lib/libdb_cxx.a
libtool: install: ranlib /usr/home/rtwair/lux/db4/lib/libdb_cxx.a
Installing DB utilities: /usr/home/rtwair/lux/db4/bin ...
libtool: install: cp -p db_archive /usr/home/rtwair/lux/db4/bin/db_archive
libtool: install: cp -p db_checkpoint /usr/home/rtwair/lux/db4/bin/db_checkpoint
libtool: install: cp -p db_deadlock /usr/home/rtwair/lux/db4/bin/db_deadlock
libtool: install: cp -p db_dump /usr/home/rtwair/lux/db4/bin/db_dump
libtool: install: cp -p db_hotbackup /usr/home/rtwair/lux/db4/bin/db_hotbackup
libtool: install: cp -p db_load /usr/home/rtwair/lux/db4/bin/db_load
libtool: install: cp -p db_printlog /usr/home/rtwair/lux/db4/bin/db_printlog
libtool: install: cp -p db_recover /usr/home/rtwair/lux/db4/bin/db_recover
libtool: install: cp -p db_sql /usr/home/rtwair/lux/db4/bin/db_sql
libtool: install: cp -p db_stat /usr/home/rtwair/lux/db4/bin/db_stat
libtool: install: cp -p db_upgrade /usr/home/rtwair/lux/db4/bin/db_upgrade
libtool: install: cp -p db_verify /usr/home/rtwair/lux/db4/bin/db_verify
Installing documentation: /usr/home/rtwair/lux/db4/docs ...

db4 build complete.

When compiling bitcoind, run `./configure` in the following way:

  export BDB_PREFIX='/usr/home/rtwair/lux/db4'
  ./configure LDFLAGS="-L${BDB_PREFIX}/lib/" CPPFLAGS="-I${BDB_PREFIX}/include/" ...`



The BDB_PREVIX environment variable is correctly set
`[rtwair@wallet ~/lux]$ echo ${BDB_PREFIX}
/usr/home/rtwair/lux/db4`

I've followed the instructions and now I can't get past the ./configure portion:.

As per the readme I'm using the following:.
`./configure BDB_CFLAGS="-I${BDB_PREFIX}/include" BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx"`

The error I get is:.
`checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing`

**Comment by rtwair** [comment]
also tried invoking configure with the absolute paths and since there wasn't a BDB_CFLAGS var in the makefile but instead BDB_CPPFLAGS:.

```
[rtwair@wallet ~/lux]$ ./configure BDB_CPPFLAGS="-I/home/rtwair/lux/db4/include" BDB_LIBS="-L/home/rtwair/lux/db4/lib -ldb_cxx"
```

same error and the config.log shows the following for those vars:.
```
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing
```

it doesn't look like those vars are being invoked:.
```
[rtwair@wallet ~/lux]$ egrep "BDB_LIBS|BDB_CPPFLAGS|BDB_CFLAGS" config.log
  $ ./configure BDB_CPPFLAGS=-I/home/rtwair/lux/db4/include BDB_LIBS=-L/home/rtwair/lux/db4/lib -ldb_cxx
BDB_CPPFLAGS=''
BDB_LIBS=''
```

I'm also attaching the .config.log file for your reference.
[config.log](https://github.com/216k155/lux/files/1652771/config.log)

**Comment by rtwair** [comment]
UPDATE:.

I re-ran ./configure using the flags that BDB recommended
```
[rtwair@wallet ~/lux]$ ./configure LDFLAGS="-L${BDB_PREFIX}/lib/" CPPFLAGS="-I${BDB_PREFIX}/include/"
```

and ./configure completes successfully however when I try to run gmake the compile fails with 3 errors:.
```
1 warning generated.
  CXX      libbitcoin_server_a-leveldbwrapper.o
  CXX      libbitcoin_server_a-main.o
In file included from main.cpp:25:
In file included from ./spork.h:41:
In file included from ./darksend.h:11:
In file included from ./activemasternode.h:15:
./wallet.h:1130:44: warning: comparison of constant 'ISMINE_SPENDABLE' (4) with expression of type 'bool' is always true [-Wtautological-constant-out-of-range-compare]
            if (pwallet->IsMine(parentOut) != ISMINE_SPENDABLE)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~
main.cpp:2272:81: warning: variable 'nCoinAge' is uninitialized when used here [-Wuninitialized]
        int64_t nCalculatedStakeReward = GetProofOfStakeReward(pindex->nHeight, nCoinAge, nFees);
                                                                                ^~~~~~~~
main.cpp:2268:26: note: initialize the variable 'nCoinAge' to silence this warning
        uint64_t nCoinAge;
                         ^
                          = 0
2 warnings generated.
  CXX      libbitcoin_server_a-merkleblock.o
  CXX      libbitcoin_server_a-miner.o
In file included from miner.cpp:22:
In file included from ./wallet.h:24:
In file included from ./darksend.h:11:
./activemasternode.h:56:12: error: use of undeclared identifier 'COutput'
    vector<COutput> SelectCoinsMasternode();
           ^
./activemasternode.h:57:12: error: use of undeclared identifier 'COutput'
    vector<COutput> SelectCoinsMasternodeForPubKey(std::string collateralAddress);
           ^
./activemasternode.h:58:27: error: unknown type name 'COutput'
    bool GetVinFromOutput(COutput out, CTxIn& vin, CPubKey& pubkey, CKey& secretKey);
                          ^
In file included from miner.cpp:22:
./wallet.h:1130:44: warning: comparison of constant 'ISMINE_SPENDABLE' (4) with expression of type 'bool' is always true [-Wtautological-constant-out-of-range-compare]
            if (pwallet->IsMine(parentOut) != ISMINE_SPENDABLE)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~
1 warning and 3 errors generated.
gmake[2]: *** [Makefile:3865: libbitcoin_server_a-miner.o] Error 1
gmake[2]: Leaving directory '/usr/home/rtwair/lux/src'
gmake[1]: *** [Makefile:6990: all-recursive] Error 1
gmake[1]: Leaving directory '/usr/home/rtwair/lux/src'
gmake: *** [Makefile:592: all-recursive] Error 1
```

Any suggestions?

Thanks again!

**Comment by rtwair** [comment]
@rej156 This was closed without any suggestions?
