### ISSUE TITLE
Wallet not starting (arch based distrib)

### ISSUE THREAD

**Issue by carlphilipp** [216k155/lux#35]
Hi,

Just downloaded the last version of the linux wallet (3.0.4), trying to run it on my arch based distro, but obtain an error right away:

▶ ./lux-qt 
./lux-qt: error while loading shared libraries: libminiupnpc.so.10: cannot open shared object file: No such file or directory

Thanks

**Comment by CMUnreal** [comment]
Same problem with manual attempt to build under Xubuntu following the officially published "Howto", and same issue as Carl Philipp outlines above.

**Comment by oliveskin** [comment]
Please try installing the missing depends.

apt-get instal -y libboost-all-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev

**Comment by carlphilipp** [comment]
Sounds like it should fix it for ubuntu, not for arch. I tried to install some packages: boost and boost-libs but it did not help.

**Comment by oliveskin** [comment]
Please check the readme - instructions have been updated.
https://github.com/216k155/lux/blob/master/README.md

Leaving the comment open until you can confirm

**Comment by rej156** [comment]
@carlphilipp compile boost from source if not tbh

**Comment by carlphilipp** [comment]
@oliveskin I appreciate the update, but it does not fundamentally resolve the issue. Even if I could compile it from git, the release still would not work. 
I tried to build it from scratch btw, and I have an error: 

```
▶ ./configure --without-miniupnpc --disable-tests  --with-incompatible-bdb
...
configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!
```

**Comment by rej156** [comment]
@carlphilipp did some scouring and found this
https://github.com/bitconnectcoin/bitconnectcoin/issues/3
Any luck trying the symbolic link with your package manager installed miniupnpc?

https://bbs.archlinux.org/viewtopic.php?id=165454
https://bugs.archlinux.org/task/35852
https://www.archlinux.org/packages/community/x86_64/miniupnpc/files/

e.g. if you have /usr/lib/libminiupnpc.so.16,
Run sudo ln -s libminiupnpc.so.16 libminiupnpc.so.10

**Comment by carlphilipp** [comment]
I think creating the symbolic link helped going further. I now have another similar error:
```
▶ ./lux-qt 
./lux-qt: error while loading shared libraries: libdb_cxx-4.8.so: cannot open shared object file: No such file or directory
```
I tried to fix it quickly but I don't really have time to spend more time. `libdb_cxx-4.8.so` is not on my system, I have `libdb_cxx-5.3.so` which is I believe from arch (manjaro exactly) last version of the Berkeley DB.

**Comment by rej156** [comment]
SYMBOLIC LINK THEM ALL
