### ISSUE TITLE
Win Wallet not syncing following official "Howto"

### ISSUE THREAD

**Issue by CMUnreal** [216k155/lux#36]
I had to manually add the lux.conf file, linked at sidebar here "reddit" to make the wallet sync beyond 14 weeks 
See sidebar link titled "lux.conf"
https://www.reddit.com/r/LUXCoin/comments/7rx6zi/lux_wallet_out_of_sync_after_pasting_bootstrap

The official Howto also linked at the reddit sidebar (links to https://drive.google.com/file/d/14HBwkHMZUqT5G53MzHxkhYBLDhVSHRcw/view does not mention the lux.conf )

**Comment by oliveskin** [comment]
Please use the bootstrap file to sync.
Team on Discord/Telegram can help if you can head over there.

New wallet will fix these issues.
