### ISSUE TITLE
Win wallet NOT RESPONDONG

### ISSUE THREAD

**Issue by 008** [216k155/lux#37]
NOT RESPONDONG
cant use it

**Comment by oliveskin** [comment]
Please head over to our discord/telegram channels so that we can help.
Do not compile the master as it is actively worked on. The 3.0.4 build works - if there are issues we do have some fixes. The release on 25th should fix lag errors.

Thanks

**Comment by 008** [comment]
1. no one can ask in telegram.
2. (3.0.4) Win veruis lags and not responding, and now its 0 connections.
3. This ticket about BAD or WRONG build on linux instruction and its dosnt resolwed, i dont know how to buid "not master" if you about this. I am investor not programmer but i can use instrustion if theay are good but thay are not.
