### ISSUE TITLE
"Build on Ubuntu"

### ISSUE THREAD

**Issue by 008** [216k155/lux#38]
instrustion very old or neverer working i dont know but now its useless, many errors and fails if you try too use it

**Comment by 008** [comment]
so, this #38 and #37 and no one can use wallet exept MAC (dosnt know about mac)
PLUS
email = no answear
win wallet = hangs, not responding, laggs etc
batcointalk = post deleding
ubuntu = old coimpile instruction, many errors and fails
twiter = no answear
= no dev feedback

lux = useless scam and shit coin ?

**Comment by oliveskin** [comment]
Please head over to our discord/telegram channels so that we can help.
Do not compile the master as it is actively worked on. The 3.0.4 build works - if there are issues we do have some fixes. The release on 25th should fix lag errors.

Thanks
