### ISSUE TITLE
MacOSX 10.12.6 - Wallet Qt 3.0.4 not syncing

### ISSUE THREAD

**Issue by osvathrobi** [216k155/lux#39]
I am using the Mac client downloaded from releases. I have tried over and over again but the client doesn't want to sync at all. It stops at 0 blocks saying "Synchronizing with network". If I use the bootstrap then it stops at block 86126. I have found this in the logs:

```
Loading addresses from DNS seeds (could take a while)
4 addresses found from DNS seeds
dnsseed thread exit
socket recv error 54
socket recv error 54
socket recv error 54
socket recv error 54
socket recv error 54
connect() to 136.243.89.142:28666 failed after select(): Connection refused
```

Is there something I could try to do to fix it on OSX? I tried the client on windows (Booted on the same Mac) and it works just fine.

**Comment by rej156** [comment]
@osavthrobi worst case scenario, please install Wine on Mac and use the Windows wallet on your Mac.

**Comment by osvathrobi** [comment]
It's all good, just thought I'd mention the issue :) Thanks

**Comment by rej156** [comment]
New Mac wallet incoming!
Can't wait myself! 
Hope all's good man, you won't have any issues like this again cross fingers in a week or so sir

**Comment by bioharz** [comment]
It's the same with the windows wallet!
