### ISSUE TITLE
mac dmg does not mount

### ISSUE THREAD

**Issue by rqueue** [216k155/lux#41]
When I open the `.dmg` for mac, I get this error saying there is "no mountable file systems"
![screen shot 2018-01-23 at 1 31 49 am](https://user-images.githubusercontent.com/3751955/35261248-58b17de8-ffdd-11e7-906f-96db841b7a60.png)

**Comment by rej156** [comment]
Please update to high Sierra or use wine with the Windows wallet download on mac
