### ISSUE TITLE
Cannot build on Mac Sierra

### ISSUE THREAD

**Issue by playak** [216k155/lux#46]
Getting quite far, but then it ends with:

"
#define HAVE_DECL_HTOBE32 0
#define HAVE_DECL_HTOBE64 0
#define HAVE_VISIBILITY_ATTRIBUTE 1

configure: exit 1
make: *** No rule to make target `deploy'.  Stop.
Build failure. Verbose build follows.
make: *** No rule to make target `deploy'.  Stop.
"

Any idea anyone?

**Comment by rej156** [comment]
Don't build master until the release announcement, master unstable atm sir
Give a few hours and we'll update the releases page with the new builds.
