### ISSUE TITLE
MineGneesis(genesis)  :fail to compile 

### ISSUE THREAD

**Issue by Singman33** [216k155/lux#5]
Error :

> g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/home/eric/developpement/phy-lux/lux/src -I/home/eric/developpement/phy-lux/lux/src/obj -DUSE_UPNP=1 -DENABLE_WALLET -I/home/eric/developpement/phy-lux/lux/src/leveldb/include -I/home/eric/developpement/phy-lux/lux/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/txdb-leveldb.d -o obj/txdb-leveldb.o txdb-leveldb.cpp
chainparams.cpp: In constructor ‘CMainParams::CMainParams()’:
chainparams.cpp:90:21: error: ‘MineGenesis’ was not declared in this scope
  MineGenesis(genesis);

**Comment by vtnplus** [comment]
hainparams.cpp: In constructor 'CMainParams::CMainParams()':
chainparams.cpp:90:21: error: 'MineGenesis' was not declared in this scope
  MineGenesis(genesis);
                     ^
makefile.unix:213: recipe for target 'obj/chainparams.o' failed

not good develop

**Comment by 216k155** [comment]
you need to deleted the whole lux folder. then git clone again.

**Comment by vtnplus** [comment]
all is new.
but get error hainparams.cpp: In constructor 'CMainParams::CMainParams()':
chainparams.cpp:90:21: error: 'MineGenesis' was not declared in this scope
MineGenesis(genesis); 

error by your not include memory defiend
