### ISSUE TITLE
Cloning recursively error with submodule

### ISSUE THREAD

**Issue by jc21** [216k155/lux#50]
Hi, following the readme build instructions, I'm getting this:

```
fatal: no submodule mapping found in .gitmodules for path 'contrib/gitian-builder'
```

And found this commit:

```bash
$ git ls-files --stage | grep 160000
160000 e2172de865fe5d3b039e92844bcd1ae830e12cd2 0       contrib/gitian-builder
```

It seems that you've got a submodule folder but no `.gitmodule` file for it. Not sure if that's a mistake or not, if it's not required the solution is to `git rm contrib/gitian-builder`

**Comment by rej156** [comment]
@216k155 
He speaks truth
