### ISSUE TITLE
Fail to build after last code update 4af452f 

### ISSUE THREAD

**Issue by gamaraan** [216k155/lux#66]
Last code update changed a lot of functions definitions in wallet (wallet.h and wallet.cpp), but the tests in test/wallet_tests.cpp where not updated to reflect the changes, and compiling the code fails because of that.

**Comment by oliveskin** [comment]
Please do not compile from master or the branches. All of them are being worked on in prep for the upgrade.
If you need a wallet , please download from https://github.com/216k155/lux/releases/tag/v3.0.4
