### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by 008** [216k155/lux#68]
v4.0.0.0-9b05712-dirty (32-bit)
12% CPU usage I7 6700k (Windows 10  64bit)

WTF? Not so far from you v3.0 wallet...
we will stake with 12% i7 CPU ???

**Comment by oliveskin** [comment]
Not sure what you are running - we are seeing below 2-5% loads.
Also,  please do not abuse on this page, keep it civil.

**Comment by 008** [comment]
![cpuloadlux](https://user-images.githubusercontent.com/860351/35870061-595dbae4-0b69-11e8-8beb-40c266b92d94.png)
