### ISSUE TITLE
0 Active Connections

### ISSUE THREAD

**Issue by FREDDIERAMBO** [216k155/lux#69]
Recently updated the wallet and cant get any connections however on the previous version it worked fine
i deleted all the old files except from lux.conf and wallet.dat 

Debug window:
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: setGeometry: Unable to set geometry 5x13+363+124 on QWidgetWindow/'QLabelClassWindow'. Resulting geometry:  120x13+363+124 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 0x0, maximum size: 16777215x16777215).
GUI: libpng warning: iCCP: known incorrect sRGB profile
2018-02-05 22:58:14 GUI: "registerShutdownBlockReason: Successfully registered: LUX Core didn't yet exit safely..."
2018-02-05 22:58:14

**Comment by MKillev** [comment]
Same here. No active connections. Wallet has been open for over an hour.

**Comment by anorganix** [comment]
It seems that you are not to connect to nodes.

Make sure you:
* backup your wallet.dat
* delete everything from your Lux folder (except wallet.dat)
* start the new wallet

If this still does not solve your problem, you can jump-start the sync using some nodes from pools (add them to lux.conf file).

https://futurecoins.club/explorer/peers?id=1908
