### ISSUE TITLE
MacOS Wallet 4.0.1 is Crashing

### ISSUE THREAD

**Issue by golimpio** [216k155/lux#85]
Lux wallet is crashing when opening it. The wallet doesn't show up, just the loading screen, and when it is "done" loading, it crashes.

OS: macOS High Sierra 10.13.3

Crash report is attached.
[lux_wallet_crash_report.txt](https://github.com/216k155/lux/files/1714538/lux_wallet_crash_report.txt)

**Comment by golimpio** [comment]
I've tried to clean up the lux folder (I've only left the wallet.dat file), but it didn't make any difference.

Attached the latest log file.
[debug.log](https://github.com/216k155/lux/files/1714542/debug.log)

**Comment by rej156** [comment]
Please download the correct high Sierra DMG and do a clean folder boot
Cheers
