### ISSUE TITLE
OSX 4.2 wallet debug shows 4.0

### ISSUE THREAD

**Issue by crackfoo** [216k155/lux#96]
{
    "version" : 4000101,
    "protocolversion" : 69200,
    "walletversion" : 60000,
    "balance" : XXXXXXXXX,
    "obfuscation_balance" : 0.00000000,
    "blocks" : 189313,
    "timeoffset" : 0,
    "connections" : 15,
    "proxy" : "",
    "difficulty" : 9088.52737095,
    "testnet" : false,
    "keypoololdest" : 1516610719,
    "keypoolsize" : 1001,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00010000,
    "staking" : "activated",
    "errors" : ""
}

About Lux-qt says:LUX Core version v4.2.0.0-2908a5c (64-bit)

**Comment by rej156** [comment]
Please redownload or compile from source, cheers
